# Generated by Django 5.2.1 on 2025-05-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmessage',
            options={'ordering': ['title'], 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
    ]
